[package]
name = "translator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap={ version = "4.5.35", features = ["derive"] }
rust-translate = "0.1.3"
tokio = { version = "1.44.2", features = ["full"] }
